- name: Copy
  copy:
    src: ../../files/isucon.conf
    dest: /etc/nginx/sites-available/isucon.conf
    mode: '0644'
    backup: true

- name: Copy
  copy:
    src: ../../files/nginx.conf
    dest: /etc/nginx/nginx.conf
    mode: '0644'
    backup: true

- name: remove file
  file: 
    path: /var/log/nginx/access.log
    state: absent

- name: reloaded
  systemd:
    name: nginx
    state: reloaded